databases:
  - name: firstapp
    ipAllowList: []
    plan: free

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: firstapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false